name: Branch CI (feature/bugfix/hotfix)

on:
  push:
    branches:
      - 'feature/**'
      - 'bugfix/**'
      - 'hotfix/**'
  pull_request:
    branches:
      - 'feature/**'
      - 'bugfix/**'
      - 'hotfix/**'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x, 24.x]

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm ci
      - run: npm test
      - name: Prepare coverage
        if: ${{ matrix.node-version == '22.x' }}
        run: npm run coverage
      - name: Publish to Coveralls
        if: ${{ matrix.node-version == '22.x' }}
        uses: coverallsapp/github-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
        continue-on-error: true